### ISSUE TITLE
Enforce gas limits on vm

### ISSUE THREAD

**Issue by ethanfrey** [cosmwasm/cosmos-sdk#5]
## Summary

We use wasmer, which doesn't allow any gas charging. This is clearly a ddos vector to upload an infinite loop on a chain. We must prevent that

## Problem Definition

There are two approaches:

1. Stick with [wasmer](https://github.com/wasmerio/wasmer)

* Instrument the wasm code with [metering as in ewasm](https://github.com/ewasm/design/blob/master/metering.md)
* This code transcription must happen on the servers when the contract is created.
* Implementation here: https://github.com/ewasm/wasm-metering

2. Use [perlin life](https://github.com/perlin-network/life)

* Figure out how to get imports and exports working well there (lack of docs is why we switched to wasmer)
* Configure and pass in a gas meter when running the code

**Comment by losfair** [comment]
Hi there,

I implemented metering for both engines and here are some suggestions :)

For Wasmer, there's a middleware system and a builtin metering middleware that can be used out-of-box. See the tests in https://github.com/wasmerio/wasmer/blob/master/lib/middleware-common/src/metering.rs as an example.

For Life, please refer to Wavelet's contract engine for enabling metering and imports/exports: https://github.com/perlin-network/wavelet/blob/master/contract.go

**Comment by ethanfrey** [comment]
HI @losfair thanks for joining in. We ended up with wasmer as there were better examples on how to pass complex structs from go -> wasm -> go. And once we figured that part, it worked very well.

The metering middleware you linked is a great tip, and exactly what we need. I am still uncertain how to enable it, having only really worked with the go bindings.

We load the code and register imports via [NewInstanceWithImports](https://godoc.org/github.com/wasmerio/go-ext-wasm/wasmer#NewInstanceWithImports). I assume that "under the hood", this compiles down the byte code we provided (to native code), where we can instrument it? I saw the rust code you referred to and see it needs llvm or singlepass feature flags. But... I am not really sure how one sets that up to be exposed through the go interfaces.

I saw https://github.com/wasmerio/go-ext-wasm/blob/master/justfile#L16 which seems to be the build steps to get compile the rust wasmer into a dylib and bind it to go. Is there any docs on how to configure this / expose the middleware through to the go interface?

Zaki recommended we stick with wasmer if possible for performance improvements. I do see that https://github.com/perlin-network/wavelet has some nice examples of go bindings for a metered environment, so that is probably the simpler route. Good to study in any case.

Thanks for the links, and as said, links to docs or more info on how the go->rust binding works on `go-ext-wasm` and how to set up custom compile flags would be very useful.

**Comment by syrusakbary** [comment]
As a small note, we created a repo showcasing on how to use metering (from Rust) with the additions that @losfair commented.
https://github.com/wasmerio/ewasm-workshop

For Go, we can prioritize on adding the bindings so you can use them directly from there.
Would be great if we can sync directly (via Hangouts?) so we can plan a proper release for it! :)

**Comment by ethanfrey** [comment]
Hi @syrusakbary  That is a wonderful link as well and thank you for the offer of support. I would love to set up a call to discuss this more. We set up this repo to organize development work, following a great hackathon prototype. Since then, we have been doing some internal organization to figure out who can work on it when, etc.

We should start moving forward on this repo starting the beginning of August, and if we could set up a call the first week or two of August that would be great. I will build the rust code above (and try modifying it) before then, so I have specific questions prepared. 

You can reach me directly at (my first name) at confio dot tech
Probably best to schedule a call there.

And thanks again for the quick response and support

**Comment by jackzampolin** [comment]
I would love to help coordinate this. My email is jack {at} tendermint {dot} com! Excited to see this work moving ahead

**Comment by ethanfrey** [comment]
WIP at https://github.com/confio/wasm-bindings

Added some test code to build with and without metering and benchmark various backends.

Next steps to figure out what I want to expose to the go interface and add that to the go-wasmer build

**Comment by ethanfrey** [comment]
Update. I made two prs to help expose the metering functionality from rust to go.

https://github.com/wasmerio/wasmer/pull/736

https://github.com/wasmerio/go-ext-wasm/pull/68

**Comment by ethanfrey** [comment]
Support matrix seems to be:

| Backend  | Gas Metering  | Serialization  | Compile Speed  | Run Speed  |
|:-:|:-:|:-:|:-:|:-:|
| Singlepass  | Yes  | No  | Fast  | Slow  |
| Cranelift  | No  | Yes  | Medium  | Medium  |
| LLVM  | Yes  | Yes  | Slow  | Fast  |

I will start with LLVM support only, but ideally adopt Cranelift (when metering is added) or Singlepass (when serialization of compiled contract is supported)

**Comment by Hywan** [comment]
:+1:

**Comment by ethanfrey** [comment]
Using Singlepass now. This is enabled in confio/cosmwasm and used in confio/go-cosmwasm
